# action.yml
name: 'Verify Me'
description: 'Make a build verifiable'
inputs:
  filepath:  
    description: 'Path of file to sign'
    required: true
    default: 'output'
outputs:
  signature: # id of output
    description: 'base64 encoded signature'
  sha256: # id of output
    description: 'hex encoded sha256 hash'
  environment:
    description: base64 encoded JSON environment
  environment_signature: # id of output
    description: 'base64 encoded signature of JSON environment'
  publickey: # id of output
    description: 'publickey'
runs:
  using: 'docker'
  image: docker://us-central1-docker.pkg.dev/dlorenc-vmtest2/test/action-c177d66b852b5ae874db32aee9157a51@sha256:87695ae9fca276108ede0cd0eff99b533c48c2c26b70c7f0cc011bff1377cd79
  args:
    - ${{ inputs.filepath }}
