name: verified-builder
on: workflow_dispatch
jobs:
  verify-build:
    name: Generate verification
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the verifier action
      - name: Run build verifier
        uses: dlorenc/verifyme/action@main
        with:
          filepath: README.md
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: README.md
      - name: Upload signatures
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: verified-output/*
